name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Select the deployment target'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - staging
          - development

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  build-development:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build stagingdev
        run: npm run build:stagingdev
        env:
          VITE_BASE_PATH: /developer/test-project-react/

  build-staging:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build staging
        run: npm run build:staging
        env:
          VITE_BASE_PATH: /test-project-react/

  deploy-staging:
    needs: build-staging
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_target == 'staging'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build staging
        run: npm run build:staging
        env:
          VITE_BASE_PATH: /test-project-react/

      - name: Deploy to Staging
        run: echo "Deploying to staging environment"  # Replace with actual deploy command

  deploy-development:
    needs: build-development
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_target == 'development'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build stagingdev
        run: npm run build:stagingdev
        env:
          VITE_BASE_PATH: /developer/test-project-react/

      - name: Deploy to Development
        run: echo "Deploying to development environment"  # Replace with actual deploy command