name: CI/CD Pipeline for React Project

# Triggers
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - test
          - development
          - staging
          - production

# Global environment variables
env:
  NODE_VERSION: "20.x"

# Jobs
jobs:
  # Job 1: Install Dependencies (Shared setup)
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

  # Job 2: Build and Test (Automated, per environment)
  build-and-test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [test, development, staging, production]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build for ${{ matrix.env }}
        env:
          VITE_APP_ENV: ${{ matrix.env }}
          VITE_APP_API_URL: ${{ vars[format('API_URL_{0}', matrix.env)] }}
        run: |
          if [ "${{ matrix.env }}" = "development" ]; then
            npm run build:stagingdev
          elif [ "${{ matrix.env }}" = "staging" ]; then
            npm run build:staging
          elif [ "${{ matrix.env }}" = "test" ]; then
            npm run build:test
          elif [ "${{ matrix.env }}" = "production" ]; then
            npm run build:prod
          else
            npm run build
          fi

      # Test-related steps only for 'test' environment
      - name: Run SAST
        if: matrix.env == 'test'
        run: echo "RUN SAST" # Replace with actual SAST command when ready

      - name: Run Unit Tests
        if: matrix.env == 'test'
        run: echo "RUN UNIT TESTS" # Replace with actual test command when ready

      - name: Run Cypress Tests
        if: matrix.env == 'test'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000
        env:
          CYPRESS_ENV: ${{ matrix.env }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.env }}
          path: dist/
          retention-days: 5

  # Job 3: Deploy to GitHub Pages Root (Manual, selected environment)
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.inputs.environment }}
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # No destination_dir specified, so it deploys to the root of gh-pages branch